accelerator: ddp
backbone: resnet50
batch_size: 128
beta1: 0.5

checkpoints_dir: ./logs
dataroot: /home1/caixin/GazeData/MPKUOutput
dataset: mpku
flip: false
gpus: 4
lr: 0.0001
metric: distance
model: gaze
netGaze: iTracker
suffix: ''
visual_freq: 20

