accelerator: ddp
batch_size: 128

camera_frame_type: face
dataroot: /home1/caixin/GazeData/eve_dataset
dataset: eve
flip: false
gpus: 4
lr: 0.0001
metric: angular
model: eve
netGaze: regressor
visual_freq: 200